name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Run client tests
        working-directory: ./client
        run: npm test

      - name: Run server tests
        working-directory: ./server
        run: npm test

      - name: Deploy client to hosting service
        working-directory: ./client
        run: echo "Deploy client steps here" # Replace this with your actual deploy command

      - name: Deploy server to server environment
        working-directory: ./server
        run: echo "Deploy server steps here" # Replace this with your actual deploy command
