name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install
      working-directory: ./client

    - name: Build
      run: npm run build --if-present
      working-directory: ./client

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: client/build
        token: ${{ secrets.MY_GIYHUB_PAT }}
        CLEAN: true
